name: preflight-project

services:
  mysql:
    image: mysql:8.0
    container_name: pf-mysql
    restart: no
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pf-net

  backend:
    container_name: pf-backend
    build: .
    ports:
      - "${PORT}:3000"
    networks:
      - pf-net
    depends_on:
      - mysql
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: 3306
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_APP_USER: ${MYSQL_APP_USER}
      MYSQL_APP_PASSWORD: ${MYSQL_APP_PASSWORD}
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

    post_start:
      - command:
          [
            "sh",
            "-c",
            'npm run db:migrate | awk ''{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0; fflush(); }'' | tee -a /app/logs/migration.log',
          ]

volumes:
  mysql-data:

networks:
  pf-net:
    external: true
