name: preflight-project
services:
  frontend:
    container_name: pf-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_ENDPOINT: ${NEXT_PUBLIC_ENDPOINT}
    ports:
      - "4000:4000"
    networks:
      - preflight_pf-net

networks:
  preflight_pf-net:
    external: true
