name: preflight-project

services:
  mysql:
    image: mysql:8.0
    container_name: pf-mysql
    restart: no
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - pf-data:/var/lib/mysql
    networks:
      - pf-net

volumes:
  mysql-data:


networks:
  pf-net:
    external: true
